---
title: "Bakeries in New York City"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

rest_inspec = 
rest_inspec %>% 
  filter(grade %in% c("A", "B", "C")) %>% 
  rename("name" = "dba") %>% 
  select(building, boro, cuisine_description, name, inspection_date, 
         street, violation_description, zipcode, grade, score)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Bakeries in Washington Heights with their respective grades and violations

```{r}
rest_inspec %>% 
  filter(cuisine_description == "Bakery", 
         zipcode %in% c("10033", "10032", "10040")) %>% 
   mutate(text_label = str_c("Violation", violation_description)) %>% 
  plot_ly(x = ~name, y = ~grade, alpha = 0.5, color = ~grade, text = ~text_label,
    type = "scatter", mode = "markers", colors = "viridis")

## I would love to figure out how to do text wrapping in hover labels. 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Total Number of Bakeries By Borough

```{r}
rest_inspec %>% 
  filter(cuisine_description == "Bakery") %>% 
  group_by(boro) %>% 
  count(cuisine_description) %>% 
  mutate(boro = fct_reorder(boro, n)) %>%
  plot_ly(x = ~boro, y = ~n, color = ~boro,
          type = "bar", colors = "viridis")
```


### Average Health Score of Bakeries by Borough

```{r}
rest_inspec %>% 
  filter(cuisine_description == "Bakery") %>% 
  group_by(inspection_date, boro) %>% 
  summarize(average_score = mean(score)) %>% 
  plot_ly(x = ~boro, y = ~average_score, color = ~boro,
    type = "box", colors = "viridis")
```

